#!/bin/sh -e

set -e

## Make sure that sources.list exists.

## If it doesn't exist, we try to rescue the backup made by our
## preinst.  This allows us to survive a update from a broken package
## database that doesn't contain conffile information, like the one in
## IT2006.

if [ ! -f /etc/apt/sources.list ]; then
  if [ -f /tmp/sources.list-preinst-backup ]; then
    mv -f /tmp/sources.list-preinst-backup /etc/apt/sources.list
  else
    touch /etc/apt/sources.list
  fi
else
  rm -f /tmp/sources.list-preinst-backup || true
fi

add_sudoer ()
{
    line="$1"
    if ! grep -F -q "$line" /etc/sudoers; then
	echo "+$line"
	chmod u+w /etc/sudoers # *cough*
	echo "$line" >>/etc/sudoers
	chmod u-w /etc/sudoers
    fi
}

## Migrate some files to their new names.

migrate ()
{
    old="$1"
    new="$2"
    if [ -e "$old" -a ! -e "$new" ]; then
	echo "Migrating $old to $new"
	mv -f "$old" "$new"
    fi
}

migrate /home/user/.osso/appinstaller \
        /home/user/.osso/hildon-application-manager

migrate /etc/osso-application-installer \
        /etc/hildon-application-manager

migrate /var/lib/osso-application-installer \
        /var/lib/hildon-application-manager

if [ ! -d /var/lib/hildon-application-manager ]; then
  mkdir /var/lib/hildon-application-manager
fi
if [ ! -e /var/lib/osso-application-installer ]; then
  ln -s hildon-application-manager /var/lib/osso-application-installer
fi

HAM_STATE_DIR=/home/user/.hildon-application-manager

if [ ! -d $HAM_STATE_DIR ]; then
  mkdir $HAM_STATE_DIR
fi

if [ -e /home/user/.hildon-application-manager-state ]; then
    if [ ! -e $HAM_STATE_DIR/state ]; then
	mv /home/user/.hildon-application-manager-state \
	   $HAM_STATE_DIR/state
    else
	rm /home/user/.hildon-application-manager-state
    fi
fi

if [ -e /home/user/.hildon-application-manager.backup ]; then
    if [ ! -e $HAM_STATE_DIR/packages.backup ]; then
	mv /home/user/.hildon-application-manager.backup \
	   $HAM_STATE_DIR/packages.backup
    else
	rm /home/user/.hildon-application-manager.backup
    fi
fi

if [ -e /home/user/.hildon-application-manager-seen-updates ]; then
    if [ ! -e $HAM_STATE_DIR/seen-updates ]; then
	mv /home/user/.hildon-application-manager-seen-updates \
	   $HAM_STATE_DIR/seen-updates
    else
	rm /home/user/.hildon-application-manager-seen-updates
    fi
fi

if [ -e /home/user/.hildon-application-manager-seen-notifications ]; then
    if [ ! -e $HAM_STATE_DIR/seen-notifications ]; then
	mv /home/user/.hildon-application-manager-seen-notifications \
	   $HAM_STATE_DIR/seen-notifications
    else
	rm /home/user/.hildon-application-manager-seen-notifications
    fi
fi

if [ -e /home/user/.hildon-application-manager-available-notifications ]; then
    if [ ! -e $HAM_STATE_DIR/available-notifications ]; then
	mv /home/user/.hildon-application-manager-available-notifications \
	   $HAM_STATE_DIR/available-notifications
    else
	rm /home/user/.hildon-application-manager-available-notifications
    fi
fi

## Clean away old configuration files

rm -f /etc/osso-backup/applications/osso-application-manager.conf

update-sudoers || true

if [ -x /usr/bin/update-mime-database ]; then
 update-mime-database /usr/share/mime
fi

if [ -x /usr/bin/osso-update-category-database ]; then
 osso-update-category-database /usr/share/mime
fi

if [ -x /usr/bin/update-desktop-database ]; then
 update-desktop-database
fi

hildon-application-manager-config update || true

#DEBHELPER#

exit 0
