#! /bin/sh

## This is a small utility to control the Application Manager in
## certain common ways.

set -e

cats="/var/lib/hildon-application-manager/catalogues.backup"

if [ "$1" = "restore-catalogues" ]; then
  /usr/bin/hildon-application-manager-config add "$cats"
elif [ "$1" = "run-after-restore" ]; then
  echo Would start it
else
  echo >&2 "usage: hildon-application-manager-util restore-catalogues" 
  echo >&2 "       hildon-application-manager-util run-after-restore"
  exit 1 
fi
